export const FETCH_TRENDING_MOVIES = 'FETCH_TRENDING_MOVIES';
export type FETCH_TRENDING_MOVIES = typeof FETCH_TRENDING_MOVIES;

export const FETCH_TRENDING_MOVIES_SUCCESS = 'FETCH_TRENDING_MOVIES_SUCCESS';
export type FETCH_TRENDING_MOVIES_SUCCESS = typeof FETCH_TRENDING_MOVIES_SUCCESS;

export const FETCH_TRENDING_MOVIES_ERROR = 'FETCH_TRENDING_MOVIES_ERROR';
export type FETCH_TRENDING_MOVIES_ERROR = typeof FETCH_TRENDING_MOVIES_ERROR;

export const FETCH_MOVIE_DETAIL = 'FETCH_MOVIE_DETAIL';
export type FETCH_MOVIE_DETAIL = typeof FETCH_MOVIE_DETAIL;

export const FETCH_MOVIE_DETAIL_SUCCESS = 'FETCH_MOVIE_DETAIL_SUCCESS';
export type FETCH_MOVIE_DETAIL_SUCCESS = typeof FETCH_MOVIE_DETAIL_SUCCESS;

export const FETCH_MOVIE_DETAIL_ERROR = 'FETCH_MOVIE_DETAIL_ERROR';
export type FETCH_MOVIE_DETAIL_ERROR = typeof FETCH_MOVIE_DETAIL_ERROR;
